-- Query to capture current autovacuum configuration and vital statistics
-- FIXED for PostgreSQL versions older than 10 (e.g., 9.6)
-- Run this query BEFORE deploying the 'ALTER TABLE' changes generated by the shell script.
SELECT
-- Table identification
n.nspname AS schema_name,
c.relname AS table_name,
-- Current Autovacuum Configuration (table-level overrides)
-- Uses pg_class.reloptions with unnest() for broad compatibility
COALESCE(
    (SELECT opt 
     FROM unnest(c.reloptions) AS opt 
     WHERE opt LIKE 'autovacuum_vacuum_scale_factor=%'
    ),
    'autovacuum_vacuum_scale_factor=' || current_setting('autovacuum_vacuum_scale_factor')
) AS current_vacuum_scale_factor,

COALESCE(
    (SELECT opt 
     FROM unnest(c.reloptions) AS opt 
     WHERE opt LIKE 'autovacuum_analyze_scale_factor=%'
    ),
    'autovacuum_analyze_scale_factor=' || current_setting('autovacuum_analyze_scale_factor')
) AS current_analyze_scale_factor,

-- Dead/Live Tuple Counts
s.n_live_tup AS live_rows,
s.n_dead_tup AS dead_rows,

-- Estimated total row count (from pg_class)
c.reltuples AS estimated_row_count,

-- Last Vacuum/Analyze Times
pg_catalog.pg_size_pretty(pg_relation_size(c.oid)) AS data_size,
s.last_vacuum,
s.last_autovacuum,
s.last_analyze,
s.last_autoanalyze


FROM
pg_class c
JOIN
pg_namespace n ON n.oid = c.relnamespace
JOIN
pg_stat_user_tables s ON s.relid = c.oid
WHERE
c.relkind = 'r' -- Only include regular tables
AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
ORDER BY
s.n_dead_tup DESC;

