#!/bin/bash

input="/pg_backups/pg2pg_init_Fp/isutf8.log"

echo > badcharacter.report
echo > badcharacter.cmd

while read -r l;
do
	f=$(echo $l|awk '{print $1}'|cut -d: -f1)
	line=$(echo $l|awk '{print $3}'|cut -d, -f1)
	p=$(echo $l|awk '{print $5}'|cut -d, -f1) 
	p1=$((p-5))
	p2=$((p+5))
	if [ $p -gt 0 ];then
		if [ $line -eq 1 ]; then
			echo ${fi}: >> badcharacter.report
			dd if=/pg_backups/pg2pg_init_Fp/$f bs=1 skip=${p1} count=20 2>/dev/null | od -tx1 -c>>badcharacter.report
		fi
		cmd="echo ${f}: \$(sed -n '${line}p' /pg_backups/pg2pg_init_Fp/$f |awk '{print \$1,\$2}') \$(sed -n '${line}p' /pg_backups/pg2pg_init_Fp/$f |cut -c ${p1}-${p2})"
		echo $cmd >> badcharacter.cmd
		eval $cmd >> badcharacter.report
	fi
done < "$input"
