- name: Deploy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/15/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: '0644'

- name: Deploy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/15/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'

