- name: Deploy PostgreSQL service file
  template:
    src: ../templates/postgresql.service.j2
    dest: /usr/lib/systemd/system/postgresql.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start PostgreSQL service
  systemd:
    name: postgresql
    enabled: yes
    state: started

