-- claimsprocess.claim_core_p definition

-- Drop table

-- DROP TABLE claimsprocess.claim_core_p;

CREATE TABLE claimsprocess.claim_core_p (
	customer_id int4 NOT NULL,
	claim_id varchar(12) NOT NULL,
	process_create_ts timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	process_create_by_device varchar(15) NULL,
	process_create_by_user_id varchar(15) NOT NULL,
	process_create_by_program_id varchar(15) NOT NULL,
	process_update_ts timestamptz NULL,
	process_update_by_device_id varchar(15) NULL,
	process_update_by_user_id varchar(15) NULL,
	process_update_by_program_id varchar(15) NULL,
	file_nm varchar(8) NOT NULL,
	claim_type_cd varchar(1) NOT NULL,
	client_id int4 NOT NULL,
	group_id int4 NOT NULL,
	member_id varchar(18) NOT NULL,
	case_id varchar(18) NOT NULL,
	pharmacy_id int4 NOT NULL,
	received_dt date NULL,
	fill_dt date NULL,
	ndc_id varchar(19) NOT NULL,
	delete_ind varchar(1) NOT NULL,
	member_birth_dt date NULL,
	member_gender varchar(1) NOT NULL,
	member_relationship_cd varchar(1) NOT NULL,
	prescription_id int8 NULL,
	refill_nbr int2 NOT NULL,
	submitted_days_supply_cnt int2 NOT NULL,
	plan_prescriber_id varchar(35) NOT NULL,
	submitted_dispense_as_written_ind varchar(1) NOT NULL,
	submitted_ingredient_cost_amt numeric(11, 2) NOT NULL,
	submitted_dispense_fee_amt numeric(11, 2) NOT NULL,
	submitted_sales_tax_amt numeric(11, 2) NOT NULL,
	submitted_total_prescription_cost_amt numeric(11, 2) NOT NULL,
	submitted_copay_amt numeric(11, 2) NOT NULL,
	submitted_balance_amt numeric(11, 2) NOT NULL,
	prescription_written_dt date NULL,
	claim_status_cd int2 NOT NULL,
	plan_days_supply_cnt int2 NOT NULL,
	plan_ingredient_cost_amt numeric(11, 2) NOT NULL,
	plan_dispense_fee_amt numeric(11, 2) NOT NULL,
	plan_calculated_copay_plus_coins_amt numeric(11, 2) NOT NULL,
	total_paid_amt numeric(11, 2) NOT NULL,
	adjudicated_amt numeric(11, 2) NOT NULL,
	approved_amt numeric(11, 2) NOT NULL,
	plan_client_administrative_expense_amt numeric(11, 2) NOT NULL,
	plan_withhold_fee_amt numeric(11, 2) NOT NULL,
	ndc_amt numeric(11, 2) NOT NULL,
	drug_class_cd varchar(1) NOT NULL,
	dea_cd varchar(1) NOT NULL,
	standard_class_cd varchar(2) NOT NULL,
	gcn_id int4 NULL,
	generic_ind varchar(1) NOT NULL,
	generic_product_ind varchar(1) NOT NULL,
	standard_therapy_class_cd varchar(2) NOT NULL,
	generic_therapy_class_cd varchar(2) NOT NULL,
	ndc_label_nm varchar(30) NOT NULL,
	member_effective_begin_dt date NULL,
	member_effective_end_dt date NULL,
	postpay_ind_1 varchar(1) NULL,
	prepay_review_ind varchar(1) NULL,
	reversal_pos_id int8 NULL,
	reversal_pos_ts timestamptz NULL,
	member_miscellaneous_data_1 varchar(10) NOT NULL,
	flex_report_cd varchar(10) NOT NULL,
	member_patient_nm varchar(30) NOT NULL,
	pharmacy_nm varchar(30) NOT NULL,
	pharmacy_affiliation_id int4 NOT NULL,
	active_ind varchar(1) NULL,
	nightly_process_ind varchar(1) NOT NULL,
	inquiry_access_ind varchar(1) NULL,
	hold_status_ind varchar(1) NULL,
	cics_claim_status_cd varchar(3) NOT NULL,
	member_reimbursement_ind varchar(1) NOT NULL,
	record_source_ind varchar(1) NOT NULL,
	pcp_id int4 NOT NULL,
	pcp_suffix int2 NOT NULL,
	scp_id int4 NOT NULL,
	scp_suffix int2 NOT NULL,
	adjusted_dt date NULL,
	partial_fill_copay_ind varchar(1) NULL,
	tier_nbr int4 NULL,
	used_external_group varchar(30) NOT NULL,
	ect_batch_nbr int4 NOT NULL,
	member_deductible_cost_amt numeric(11, 2) NOT NULL,
	member_deductible_plan_ind varchar(1) NOT NULL,
	pricing_module_program varchar(8) NOT NULL,
	pricing_module_version int2 NOT NULL,
	dosage_strength varchar(10) NOT NULL,
	package_size numeric(11, 3) NOT NULL,
	specific_therapy_class_cd varchar(3) NULL,
	ndc_format_ind int2 NOT NULL,
	standard_package_ind int2 NOT NULL,
	ahfs_therapy_class int4 NOT NULL,
	deductible_status_ind varchar(1) NOT NULL,
	prescription_origin_cd varchar(1) NULL,
	prescription_reason_cd varchar(2) NULL,
	submitted_member_id varchar(20) NOT NULL,
	submitted_member_person_cd varchar(3) NOT NULL,
	ndc_drug_category_cd varchar(1) NOT NULL,
	pricing_type_ind varchar(2) NOT NULL,
	price_source_ind varchar(1) NULL,
	formulary_ind varchar(1) NULL,
	submitted_prescriber_id varchar(35) NOT NULL,
	wc_injury_dt date NULL,
	wc_file_nbr varchar(20) NOT NULL,
	wc_claim_representative varchar(27) NOT NULL,
	wc_employer varchar(27) NOT NULL,
	calculated_submitted_balance_amt numeric(11, 2) NOT NULL,
	report_exclusion_ind varchar(1) NOT NULL,
	chronic_medication_scripts int2 NOT NULL,
	prudential_medicare_ind varchar(1) NOT NULL,
	prudential_division_cd varchar(2) NOT NULL,
	prudential_product_cd varchar(1) NOT NULL,
	prudential_contract_nbr varchar(5) NOT NULL,
	prudential_branch_nbr varchar(4) NOT NULL,
	prudential_charts_plan varchar(4) NOT NULL,
	adjudication_cd varchar(2) NULL,
	customized_formulary_ind varchar(1) NULL,
	lics_ind varchar(1) NULL,
	lis_level int2 NULL,
	lis_effective_begin_dt date NULL,
	lis_effective_end_dt date NULL,
	awp_ingredient_cost_amt numeric(11, 2) NOT NULL,
	customer_calculated_ingredient_cost_amt numeric(11, 2) NOT NULL,
	customer_calculated_dispense_fee_amt numeric(11, 2) NOT NULL,
	customer_calculated_sales_tax_amt numeric(11, 2) NOT NULL,
	customer_calculated_copay_amt numeric(11, 2) NOT NULL,
	preauthorization_nbr int8 NOT NULL,
	ndc_manufacturer_nm varchar(15) NOT NULL,
	deductible_applied_ingredient_cost_amt numeric(11, 2) NOT NULL,
	deductible_applied_dispense_fee_amt numeric(11, 2) NOT NULL,
	deductible_applied_sales_tax_amt numeric(11, 2) NOT NULL,
	compound_cd int2 NOT NULL,
	refills_authorized int2 NOT NULL,
	prior_authorization_cd int2 NOT NULL,
	primary_prescriber varchar(35) NOT NULL,
	clinic_id int4 NOT NULL,
	basis_of_cost int2 NOT NULL,
	diagnosis_cd varchar(6) NOT NULL,
	member_pay_difference_amt numeric(11, 2) NOT NULL,
	associated_claim_id varchar(12) NOT NULL,
	dual_member_ind varchar(1) NOT NULL,
	dual_coverage_ind varchar(1) NOT NULL,
	medicaid_cost_amt numeric(11, 2) NOT NULL,
	member_record_status_ind varchar(1) NOT NULL,
	member_miscellaneous_data_2 varchar(15) NOT NULL,
	member_miscellaneous_data_3 varchar(15) NOT NULL,
	mac_ingredient_cost_amt numeric(11, 2) NOT NULL,
	provider_status_cd varchar(2) NOT NULL,
	member_cardholder_nm varchar(30) NOT NULL,
	credit_card_nbr varchar(20) NOT NULL,
	credit_card_expiration_dt int4 NOT NULL,
	matched_dt date NULL,
	quantity_rounding_cd int2 NOT NULL,
	presented_for_billing_ind varchar(1) NOT NULL,
	drug_interaction_ind varchar(1) NOT NULL,
	duplicate_therapy_ind varchar(1) NOT NULL,
	drug_of_preference_ind varchar(1) NOT NULL,
	dosage_range_check_ind varchar(1) NOT NULL,
	member_history_created_ind varchar(1) NOT NULL,
	originating_region varchar(4) NOT NULL,
	network_ind varchar(1) NOT NULL,
	member_deductible_applied_amt numeric(11, 2) NOT NULL,
	plan_deductible_applied_amt numeric(11, 2) NOT NULL,
	alternate_member_id varchar(18) NOT NULL,
	benefit_plan_id varchar(9) NOT NULL,
	override_copay_ind varchar(1) NOT NULL,
	override_copay_amt numeric(11, 2) NOT NULL,
	override_copay_prct numeric(3, 2) NOT NULL,
	member_network_ind varchar(1) NOT NULL,
	match_received_dt date NULL,
	match_control_nbr int4 NOT NULL,
	match_line_nbr int4 NOT NULL,
	match_ind varchar(1) NULL,
	match_received_julian_dt int4 NOT NULL,
	alternate_business varchar(1) NOT NULL,
	therapy_protocol_ind varchar(1) NOT NULL,
	claim_added_category varchar(1) NOT NULL,
	claim_updated_category varchar(1) NOT NULL,
	usual_and_customary_amt numeric(11, 2) NOT NULL,
	prescriber_specialty_cd varchar(4) NOT NULL,
	submitted_birth_dt date NULL,
	restricted_authorization_nbr int8 NOT NULL,
	customized_authorization_nbr int8 NOT NULL,
	report_for_rebate_ind varchar(1) NOT NULL,
	drug_age_conflict_ind varchar(1) NOT NULL,
	drug_disease_ind varchar(1) NOT NULL,
	drug_allergy_ind varchar(1) NOT NULL,
	refill_too_soon_ind varchar(1) NOT NULL,
	prescriber_plan_id varchar(9) NOT NULL,
	cost_plan_nm varchar(9) NOT NULL,
	pharmacy_plan_id varchar(10) NOT NULL,
	network_id int4 NOT NULL,
	submitted_preauthorization_nbr varchar(35) NULL,
	submitted_metric_decimal_qty numeric(11, 3) NOT NULL,
	plan_metric_decimal_qty numeric(11, 3) NOT NULL,
	override_module_nm varchar(8) NOT NULL,
	override_module_version int2 NOT NULL,
	deductible_excluded_amt numeric(11, 2) NOT NULL,
	coverage_cd_1 varchar(6) NOT NULL,
	coverage_cd_2 varchar(6) NOT NULL,
	plan_group_cd varchar(4) NOT NULL,
	city_cd varchar(3) NOT NULL,
	copay_source_cd varchar(1) NOT NULL,
	wac_ingredient_cost_amt numeric(11, 2) NOT NULL,
	plan_copay_amt numeric(11, 2) NOT NULL,
	partial_fill_claim_id varchar(12) NOT NULL,
	dispensing_status_ind varchar(1) NOT NULL,
	associated_prescription_id int8 NOT NULL,
	associated_prescription_service_dt date NULL,
	intended_to_be_dispensed_qty numeric(11, 3) NOT NULL,
	intended_to_be_dispensed_days_supply_cnt int2 NOT NULL,
	basis_calculated_dispense_fee_cd varchar(2) NOT NULL,
	basis_calculated_copay_cd varchar(2) NOT NULL,
	orange_book_cd varchar(2) NOT NULL,
	pharmacy_chain_id int4 NOT NULL,
	partial_fill_dispense_fee_amt numeric(11, 2) NOT NULL,
	savings_fee_amt numeric(11, 3) NOT NULL,
	gpi_claim_status_ind varchar(1) NOT NULL,
	original_plan_allowed_amt numeric(11, 2) NOT NULL,
	other_payer_recognized_amt numeric(11, 2) NOT NULL,
	cob_ind varchar(1) NOT NULL,
	medicaid_agency_id varchar(8) NOT NULL,
	medicaid_claim_id varchar(20) NOT NULL,
	medicaid_patient_id_qualifier int2 NOT NULL,
	medicaid_patient_id varchar(11) NOT NULL,
	alternate_total_paid_amt numeric(11, 2) NOT NULL,
	alternate_patient_pay_amt numeric(11, 2) NOT NULL,
	alternate_ingredient_cost_amt numeric(11, 2) NOT NULL,
	alternate_sales_tax_amt numeric(11, 2) NOT NULL,
	alternate_dispense_fee_amt numeric(11, 2) NOT NULL,
	cob_applied_amt numeric(11, 2) NOT NULL,
	pos_rebate_amt numeric(11, 2) NOT NULL,
	cms_processed_ind varchar(1) NOT NULL,
	internal_processing_amt numeric(11, 2) NOT NULL,
	customer_processing_amt numeric(11, 2) NOT NULL,
	rebate_invoice_manufacturer_amt numeric(11, 2) NOT NULL,
	administrative_fee_amt numeric(11, 2) NOT NULL,
	income_ind varchar(1) NOT NULL,
	rebate_ind varchar(1) NOT NULL,
	rebate_price_source_ind varchar(1) NOT NULL,
	manufacturer_administrative_fee_ind varchar(1) NOT NULL,
	rebate_used_pct numeric(11, 8) NOT NULL,
	hra_applied_amt numeric(11, 2) NOT NULL,
	hsa_applied_amt numeric(11, 2) NOT NULL,
	fsa_applied_amt numeric(11, 2) NOT NULL,
	deductible_system_ind varchar(1) NOT NULL,
	pos_rebate_contract_id int4 NOT NULL,
	deductible_specific_amt numeric(11, 2) NOT NULL,
	mop_specific_amt numeric(11, 2) NOT NULL,
	plan_maximum_specific_amt numeric(11, 2) NOT NULL,
	deductible_specific_excluded_amt numeric(11, 2) NOT NULL,
	mop_specific_excluded_amt numeric(11, 2) NOT NULL,
	mpp_specific_excluded_amt numeric(11, 2) NOT NULL,
	line_of_business_cd varchar(3) NULL,
	mpd_applied_to_deductible_amt numeric(11, 2) NOT NULL,
	mpd_applied_to_mop_amt numeric(11, 2) NOT NULL,
	specialty_drug_ind varchar(1) NOT NULL,
	drug_discount_ind varchar(1) NOT NULL,
	pca_rollover_amt numeric(11, 2) NOT NULL,
	mac_unit_cost numeric(11, 2) NOT NULL,
	pca_allowance_amt numeric(11, 2) NOT NULL,
	pca_allowance_percent_amt numeric(11, 2) NOT NULL,
	total_member_liability_amt numeric(11, 2) NOT NULL,
	total_plan_liability_amt numeric(11, 2) NOT NULL,
	therapy_protocol_nm varchar(6) NOT NULL,
	protocol_type_cd_01 varchar(2) NOT NULL,
	protocol_type_cd_02 varchar(2) NOT NULL,
	protocol_type_cd_03 varchar(2) NOT NULL,
	protocol_type_cd_04 varchar(2) NOT NULL,
	protocol_type_cd_05 varchar(2) NOT NULL,
	protocol_type_cd_06 varchar(2) NOT NULL,
	protocol_type_cd_07 varchar(2) NOT NULL,
	protocol_type_cd_08 varchar(2) NOT NULL,
	protocol_type_cd_09 varchar(2) NOT NULL,
	protocol_type_cd_10 varchar(2) NOT NULL,
	deductible_status_ind_2 varchar(2) NOT NULL,
	post_processing_fee_amt numeric(11, 2) NOT NULL,
	postpay_ind_2 varchar(1) NOT NULL,
	postpay_ind_3 varchar(1) NOT NULL,
	postpay_ind_4 varchar(1) NOT NULL,
	troop_eligibility_ind varchar(1) NOT NULL,
	other_troop_amt numeric(11, 2) NOT NULL,
	plro_amt numeric(11, 2) NOT NULL,
	lis_cd varchar(5) NOT NULL,
	lis_amt numeric(11, 2) NOT NULL,
	troop_applied_amt numeric(11, 2) NOT NULL,
	network_differential_amt numeric(11, 2) NOT NULL,
	mtm_cd varchar(5) NOT NULL,
	mtm_effective_begin_dt date NULL,
	institutional_cd varchar(5) NOT NULL,
	institutional_effective_begin_dt date NULL,
	prescriber_id_qualifier_cd varchar(2) NOT NULL,
	pharmacy_id_qualifier varchar(2) NOT NULL,
	cms_transaction_reference_nbr varchar(30) NULL,
	paid_professional_service_amt numeric(11, 2) NOT NULL,
	submitted_professional_service_fee_amt numeric(11, 2) NOT NULL,
	incentive_paid_amt numeric(11, 2) NOT NULL,
	formatted_diagnosis_cd_1 varchar(15) NOT NULL,
	formatted_diagnosis_cd_2 varchar(15) NOT NULL,
	formatted_diagnosis_cd_3 varchar(15) NOT NULL,
	formatted_diagnosis_cd_4 varchar(15) NOT NULL,
	formatted_diagnosis_cd_5 varchar(15) NOT NULL,
	formatted_diagnosis_cd_qualifier_1 varchar(2) NOT NULL,
	formatted_diagnosis_cd_qualifier_2 varchar(2) NOT NULL,
	formatted_diagnosis_cd_qualifier_3 varchar(2) NOT NULL,
	formatted_diagnosis_cd_qualifier_4 varchar(2) NOT NULL,
	formatted_diagnosis_cd_qualifier_5 varchar(2) NOT NULL,
	dur_conflict_cd_1 varchar(2) NOT NULL,
	dur_conflict_cd_2 varchar(2) NOT NULL,
	dur_conflict_cd_3 varchar(2) NOT NULL,
	dur_conflict_cd_4 varchar(2) NOT NULL,
	dur_conflict_cd_5 varchar(2) NOT NULL,
	dur_conflict_cd_6 varchar(2) NOT NULL,
	dur_conflict_cd_7 varchar(2) NOT NULL,
	dur_conflict_cd_8 varchar(2) NOT NULL,
	dur_conflict_cd_9 varchar(2) NOT NULL,
	dur_intervention_cd_1 varchar(2) NOT NULL,
	dur_intervention_cd_2 varchar(2) NOT NULL,
	dur_intervention_cd_3 varchar(2) NOT NULL,
	dur_intervention_cd_4 varchar(2) NOT NULL,
	dur_intervention_cd_5 varchar(2) NOT NULL,
	dur_intervention_cd_6 varchar(2) NOT NULL,
	dur_intervention_cd_7 varchar(2) NOT NULL,
	dur_intervention_cd_8 varchar(2) NOT NULL,
	dur_intervention_cd_9 varchar(2) NOT NULL,
	dur_outcome_cd_1 varchar(2) NOT NULL,
	dur_outcome_cd_2 varchar(2) NOT NULL,
	dur_outcome_cd_3 varchar(2) NOT NULL,
	dur_outcome_cd_4 varchar(2) NOT NULL,
	dur_outcome_cd_5 varchar(2) NOT NULL,
	dur_outcome_cd_6 varchar(2) NOT NULL,
	dur_outcome_cd_7 varchar(2) NOT NULL,
	dur_outcome_cd_8 varchar(2) NOT NULL,
	dur_outcome_cd_9 varchar(2) NOT NULL,
	dur_pps_level_effort_1 varchar(2) NOT NULL,
	dur_pps_level_effort_2 varchar(2) NOT NULL,
	dur_pps_level_effort_3 varchar(2) NOT NULL,
	dur_pps_level_effort_4 varchar(2) NOT NULL,
	dur_pps_level_effort_5 varchar(2) NOT NULL,
	dur_pps_level_effort_6 varchar(2) NOT NULL,
	dur_pps_level_effort_7 varchar(2) NOT NULL,
	dur_pps_level_effort_8 varchar(2) NOT NULL,
	dur_pps_level_effort_9 varchar(2) NOT NULL,
	dur_co_agent_qualifier_1 varchar(2) NOT NULL,
	dur_co_agent_qualifier_2 varchar(2) NOT NULL,
	dur_co_agent_qualifier_3 varchar(2) NOT NULL,
	dur_co_agent_qualifier_4 varchar(2) NOT NULL,
	dur_co_agent_qualifier_5 varchar(2) NOT NULL,
	dur_co_agent_qualifier_6 varchar(2) NOT NULL,
	dur_co_agent_qualifier_7 varchar(2) NOT NULL,
	dur_co_agent_qualifier_8 varchar(2) NOT NULL,
	dur_co_agent_qualifier_9 varchar(2) NOT NULL,
	dur_co_agent_id_1 varchar(40) NULL,
	dur_co_agent_id_2 varchar(40) NULL,
	dur_co_agent_id_3 varchar(40) NULL,
	dur_co_agent_id_4 varchar(40) NULL,
	dur_co_agent_id_5 varchar(40) NULL,
	dur_co_agent_id_6 varchar(40) NULL,
	dur_co_agent_id_7 varchar(40) NULL,
	dur_co_agent_id_8 varchar(40) NULL,
	dur_co_agent_id_9 varchar(40) NULL,
	total_cob_applied_amt numeric(11, 2) NOT NULL,
	compound_dosage_description_cd varchar(15) NULL,
	compound_dispense_form_ind varchar(1) NOT NULL,
	compound_route_of_administration_cd varchar(2) NOT NULL,
	product_service_id_qualifier varchar(2) NOT NULL,
	product_service_id varchar(40) NULL,
	level_of_service_cd varchar(2) NOT NULL,
	lis_deductible_cost_amt numeric(11, 2) NOT NULL,
	drug_list_table_nm varchar(12) NOT NULL,
	npi_prescriber_id varchar(10) NOT NULL,
	npi_pharmacy_id varchar(10) NOT NULL,
	submitted_incentive_amt numeric(11, 2) NOT NULL,
	cms_transition_cd varchar(2) NOT NULL,
	adjudication_applied_amt numeric(11, 2) NOT NULL,
	spap_applied_amt numeric(11, 2) NOT NULL,
	julian_date_partition_txt varchar(7) NULL,
	claim_sequence_id int2 NOT NULL,
	supplemental_reporting_ind varchar(1) NULL,
	domani_ind bool DEFAULT false NULL,
	CONSTRAINT claim_core_p_pkey PRIMARY KEY (customer_id, claim_id,process_create_ts)
) PARTITION BY LIST (customer_id);

create index claim_core_p_idx1 on claimsprocess.claim_core_p(process_create_ts);

CREATE TABLE IF NOT EXISTS claim_core_p_default
PARTITION OF claim_core_p DEFAULT;


