# Start from the official Cassandra image
FROM cassandra:latest

RUN apt-get update && apt-get install -y openjdk-17-jdk

# Optional: set environment variables if needed
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
